site_name: "gpuma Documentation"
site_description: "Documentation for the gpuma package."
site_author: "Niklas HÃ¶lter"
site_url: "https://NiklasHoelter.github.io/gpuma/"
repo_url: https://github.com/NiklasHoelter/gpuma
repo_name: NiklasHoelter/gpuma
edit_uri: edit/main/docs/ # Allows users to suggest edits directly via GitHub

theme:
  name: "material"
  logo: "logo_round.png"
  favicon: "logo_round.png"
  features:
    - navigation.expand
    - content.code.copy
  palette:
    # Light mode
    - scheme: default
      primary: teal
      accent: purple

nav:
  - Home: index.md
  - Installation: install.md
  - Configuration: config.md
  - Command Line Interface: cli.md
  - Python API: reference.md
  - License: LICENSE.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

extra:
  python_path: .

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences # Allows nesting code blocks inside other blocks
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets # Allows you to embed code from external files